const { execute } = require('../../db/oraclePool');
const { buildStrictActiveSituacionCte, normalizedMojibakeSqlExpr } = require('./sqlFragments');

const normalized = (column) => normalizedMojibakeSqlExpr(`TO_CHAR(${column})`);
const affirmative = (column) => `${normalized(column)} LIKE 'SI%'`;

const PROCEDENCIA_SQL = `(
  ${affirmative('g.VENCIMIENTO_TERMINOS')}
  OR ${affirmative('g.UTILIDAD_PUBLICA')}
  OR ${affirmative('g.LIBERTAD_CONDICIONAL')}
  OR ${affirmative('g.PRISION_DOMICILIARIA_MITAD_PENA')}
  OR ${affirmative('g.PROCEDENCIA_PENA_CUMPLIDA')}
  OR ${affirmative('g.PROCEDENCIA_ACUMULACION_PENAS')}
  OR (
    TRIM(TO_CHAR(g.ACTUACION_ADELANTAR)) IS NOT NULL
    AND ${normalized('g.ACTUACION_ADELANTAR')} NOT LIKE 'NINGUNA%'
    AND ${normalized('g.ACTUACION_ADELANTAR')} NOT LIKE '%NO PROCEDE%'
  )
)`;

const SOLICITUD_RADICADA_SQL = `(
  g.FECHA_SOLICITUD_AUDIENCIA_CONTROL IS NOT NULL
  OR g.FECHA_PRESENTACION_SOLICITUD_AUTORIDAD IS NOT NULL
  OR g.FECHA_RADICACION_UTILIDAD IS NOT NULL
)`;

const DECISION_SQL = `(
  g.FECHA_DECISION_AUTORIDAD IS NOT NULL
  OR g.FECHA_DECISION_RECURSO IS NOT NULL
)`;

const DECISION_NO_FAVORABLE_SQL = `(
  ${normalized('g.SENTIDO_DECISION')} LIKE 'NO CONCEDE%'
  OR ${normalized('g.SENTIDO_DECISION')} LIKE 'NIEGA%'
  OR ${normalized('g.SENTIDO_DECISION')} LIKE 'DESFAVORABLE%'
  OR ${normalized('g.SENTIDO_DECISION_RESUELVE_RECURSO')} LIKE 'NO CONCEDE%'
  OR ${normalized('g.SENTIDO_DECISION_RESUELVE_RECURSO')} LIKE 'NIEGA%'
  OR ${normalized('g.SENTIDO_DECISION_RESUELVE_RECURSO')} LIKE 'DESFAVORABLE%'
)`;

const DECISION_FAVORABLE_SQL = `(
  (
    ${normalized('g.SENTIDO_DECISION')} LIKE 'CONCEDE%'
    AND ${normalized('g.SENTIDO_DECISION')} NOT LIKE 'NO CONCEDE%'
  )
  OR ${normalized('g.SENTIDO_DECISION')} LIKE 'OTORGA%'
  OR ${normalized('g.SENTIDO_DECISION')} LIKE 'FAVORABLE%'
  OR (
    ${normalized('g.SENTIDO_DECISION_RESUELVE_RECURSO')} LIKE 'CONCEDE%'
    AND ${normalized('g.SENTIDO_DECISION_RESUELVE_RECURSO')} NOT LIKE 'NO CONCEDE%'
  )
  OR ${normalized('g.SENTIDO_DECISION_RESUELVE_RECURSO')} LIKE 'OTORGA%'
  OR ${normalized('g.SENTIDO_DECISION_RESUELVE_RECURSO')} LIKE 'FAVORABLE%'
)`;

const GENERAL_REPORT_SQL = `
  ${buildStrictActiveSituacionCte()},
  asignaciones_activas AS (
    SELECT DISTINCT a.ID_PERSONA
    FROM DNDP.ASIGNACION a
    WHERE a.FECHA_FIN IS NULL
  ),
  hitos_gestion AS (
    SELECT
      g.ID_SITUACION,
      MAX(CASE WHEN g.FECHA_ANALISIS IS NOT NULL THEN 1 ELSE 0 END) AS TIENE_ANALISIS,
      MAX(CASE WHEN ${PROCEDENCIA_SQL} THEN 1 ELSE 0 END) AS TIENE_PROCEDENCIA,
      MAX(CASE WHEN g.FECHA_ENTREVISTA IS NOT NULL THEN 1 ELSE 0 END) AS TIENE_ENTREVISTA,
      MAX(CASE WHEN ${affirmative('g.DECISION_USUARIO')} THEN 1 ELSE 0 END) AS SOLICITA_ATENCION,
      MAX(CASE WHEN ${SOLICITUD_RADICADA_SQL} THEN 1 ELSE 0 END) AS TIENE_SOLICITUD,
      MAX(CASE WHEN ${DECISION_SQL} THEN 1 ELSE 0 END) AS TIENE_DECISION,
      MAX(CASE WHEN ${DECISION_SQL} AND ${DECISION_FAVORABLE_SQL} THEN 1 ELSE 0 END) AS DECISION_FAVORABLE,
      MAX(CASE WHEN ${DECISION_SQL} AND ${DECISION_NO_FAVORABLE_SQL} THEN 1 ELSE 0 END) AS DECISION_NO_FAVORABLE
    FROM DNDP.GESTION_JURIDICA g
    GROUP BY g.ID_SITUACION
  ),
  base AS (
    SELECT
      s.ID_PERSONA,
      NVL(h.TIENE_ANALISIS, 0) AS TIENE_ANALISIS,
      NVL(h.TIENE_PROCEDENCIA, 0) AS TIENE_PROCEDENCIA,
      NVL(h.TIENE_ENTREVISTA, 0) AS TIENE_ENTREVISTA,
      NVL(h.SOLICITA_ATENCION, 0) AS SOLICITA_ATENCION,
      NVL(h.TIENE_SOLICITUD, 0) AS TIENE_SOLICITUD,
      NVL(h.TIENE_DECISION, 0) AS TIENE_DECISION,
      NVL(h.DECISION_FAVORABLE, 0) AS DECISION_FAVORABLE,
      NVL(h.DECISION_NO_FAVORABLE, 0) AS DECISION_NO_FAVORABLE
    FROM ranked_situacion s
    JOIN asignaciones_activas a ON a.ID_PERSONA = s.ID_PERSONA
    LEFT JOIN hitos_gestion h ON h.ID_SITUACION = s.ID_SITUACION
    WHERE s.RN = 1
      AND NVL(s.ACTIVO, 0) = 1
  )
  SELECT
    COUNT(DISTINCT ID_PERSONA) AS USUARIOS_ASIGNADOS,
    COUNT(DISTINCT CASE WHEN TIENE_ANALISIS = 1 THEN ID_PERSONA END) AS ANALISIS_REALIZADOS,
    COUNT(DISTINCT CASE WHEN TIENE_ANALISIS = 1 AND TIENE_PROCEDENCIA = 1 THEN ID_PERSONA END) AS PROCEDE_SOLICITUD,
    COUNT(DISTINCT CASE WHEN TIENE_ANALISIS = 1 AND TIENE_PROCEDENCIA = 1 AND TIENE_ENTREVISTA = 1 THEN ID_PERSONA END) AS USUARIOS_ENTREVISTADOS,
    COUNT(DISTINCT CASE WHEN TIENE_ANALISIS = 1 AND TIENE_PROCEDENCIA = 1 AND TIENE_ENTREVISTA = 1 AND SOLICITA_ATENCION = 1 THEN ID_PERSONA END) AS USUARIOS_SOLICITAN_ATENCION,
    COUNT(DISTINCT CASE WHEN TIENE_ANALISIS = 1 AND TIENE_PROCEDENCIA = 1 AND TIENE_ENTREVISTA = 1 AND SOLICITA_ATENCION = 1 AND TIENE_SOLICITUD = 1 THEN ID_PERSONA END) AS SOLICITUDES_RADICADAS,
    COUNT(DISTINCT CASE WHEN TIENE_ANALISIS = 1 AND TIENE_PROCEDENCIA = 1 AND TIENE_ENTREVISTA = 1 AND SOLICITA_ATENCION = 1 AND TIENE_SOLICITUD = 1 AND TIENE_DECISION = 1 THEN ID_PERSONA END) AS DECISIONES_JUDICIALES,
    COUNT(DISTINCT CASE WHEN TIENE_ANALISIS = 1 AND TIENE_PROCEDENCIA = 1 AND TIENE_ENTREVISTA = 1 AND SOLICITA_ATENCION = 1 AND TIENE_SOLICITUD = 1 AND TIENE_DECISION = 1 AND DECISION_FAVORABLE = 1 THEN ID_PERSONA END) AS DECISIONES_FAVORABLES,
    COUNT(DISTINCT CASE WHEN TIENE_ANALISIS = 1 AND TIENE_PROCEDENCIA = 1 AND TIENE_ENTREVISTA = 1 AND SOLICITA_ATENCION = 1 AND TIENE_SOLICITUD = 1 AND TIENE_DECISION = 1 AND DECISION_NO_FAVORABLE = 1 AND DECISION_FAVORABLE = 0 THEN ID_PERSONA END) AS DECISIONES_NO_FAVORABLES
  FROM base
`;

async function getGeneralMetrics() {
  const result = await execute(GENERAL_REPORT_SQL, {}, { operation: 'reportes.general.snapshot' });
  return Array.isArray(result?.rows) ? result.rows[0] || {} : {};
}

module.exports = {
  GENERAL_REPORT_SQL,
  getGeneralMetrics,
};
